# Generated by Django 4.2.5 on 2023-10-01 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_league_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='pending_requests',
            field=models.ManyToManyField(related_name='pending_league_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
