# Generated by Django 4.2.5 on 2023-10-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='league',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teamposition',
            name='league',
        ),
        migrations.RemoveField(
            model_name='teamposition',
            name='team',
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
        migrations.DeleteModel(
            name='TeamPosition',
        ),
    ]
